// <auto-generated />
using System;
using E_Learning.DAL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Learning.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240905124759_wishlist add")]
    partial class wishlistadd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Learning.DAL.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "option1",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Body = "option2",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Body = "option3",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Body = "option1",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Body = "option2",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Body = "option3",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Body = "option1",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 8,
                            Body = "option2",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 9,
                            Body = "option3",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            Body = "option1",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 11,
                            Body = "option2",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 12,
                            Body = "option3",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 13,
                            Body = "option1",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 14,
                            Body = "option2",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 15,
                            Body = "option3",
                            QuestionId = 5
                        });
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Cart", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            UserId = 3,
                            CourseId = 3,
                            Id = 0
                        },
                        new
                        {
                            UserId = 4,
                            CourseId = 4,
                            Id = 0
                        });
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sporting"
                        });
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonsNo")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(2,1)");

                    b.Property<int>("SectionsNo")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreationDate = new DateTime(2024, 9, 5, 15, 47, 55, 839, DateTimeKind.Local).AddTicks(364),
                            LessonsNo = 0,
                            Price = 0m,
                            SectionsNo = 0,
                            Title = "C# From Zero To SuperHero",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreationDate = new DateTime(2024, 9, 5, 15, 47, 55, 839, DateTimeKind.Local).AddTicks(418),
                            LessonsNo = 0,
                            Price = 0m,
                            SectionsNo = 0,
                            Title = "Data Strcutre",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreationDate = new DateTime(2024, 9, 5, 15, 47, 55, 839, DateTimeKind.Local).AddTicks(420),
                            LessonsNo = 0,
                            Price = 0m,
                            SectionsNo = 0,
                            Title = "Diet",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreationDate = new DateTime(2024, 9, 5, 15, 47, 55, 839, DateTimeKind.Local).AddTicks(422),
                            LessonsNo = 0,
                            Price = 0m,
                            SectionsNo = 0,
                            Title = "GYM",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Enrollment", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CompletedLessons")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            UserId = 3,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2024, 9, 5, 15, 47, 55, 839, DateTimeKind.Local).AddTicks(8006)
                        },
                        new
                        {
                            UserId = 4,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2024, 9, 5, 16, 47, 55, 839, DateTimeKind.Local).AddTicks(8028)
                        });
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "https://",
                            SectionId = 1,
                            Title = "orientation"
                        },
                        new
                        {
                            Id = 2,
                            Content = "https://",
                            SectionId = 1,
                            Title = "introduction"
                        },
                        new
                        {
                            Id = 3,
                            Content = "https://",
                            SectionId = 2,
                            Title = "Encpsulation"
                        },
                        new
                        {
                            Id = 4,
                            Content = "https://",
                            SectionId = 2,
                            Title = "inheritance"
                        },
                        new
                        {
                            Id = 5,
                            Content = "https://",
                            SectionId = 2,
                            Title = "abstraction"
                        },
                        new
                        {
                            Id = 6,
                            Content = "https://",
                            SectionId = 2,
                            Title = "polymorphism"
                        },
                        new
                        {
                            Id = 7,
                            Content = "https://",
                            SectionId = 3,
                            Title = "intoduction"
                        },
                        new
                        {
                            Id = 8,
                            Content = "https://",
                            SectionId = 3,
                            Title = "Binary tree"
                        },
                        new
                        {
                            Id = 9,
                            Content = "https://",
                            SectionId = 4,
                            Title = "introduction"
                        },
                        new
                        {
                            Id = 10,
                            Content = "https://",
                            SectionId = 4,
                            Title = "hum ya gamal"
                        },
                        new
                        {
                            Id = 11,
                            Content = "https://",
                            SectionId = 4,
                            Title = "calories"
                        },
                        new
                        {
                            Id = 12,
                            Content = "https://",
                            SectionId = 5,
                            Title = "3ash ya wa7sh"
                        },
                        new
                        {
                            Id = 13,
                            Content = "https://",
                            SectionId = 5,
                            Title = "el3ab sa7"
                        });
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelAnswer")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Question1",
                            ModelAnswer = 1,
                            QuizId = 1
                        },
                        new
                        {
                            Id = 2,
                            Body = "Question2",
                            ModelAnswer = 2,
                            QuizId = 2
                        },
                        new
                        {
                            Id = 3,
                            Body = "Question3",
                            ModelAnswer = 3,
                            QuizId = 3
                        },
                        new
                        {
                            Id = 4,
                            Body = "Question4",
                            ModelAnswer = 2,
                            QuizId = 4
                        },
                        new
                        {
                            Id = 5,
                            Body = "Question5",
                            ModelAnswer = 1,
                            QuizId = 5
                        });
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grade = 0,
                            SectionId = 1,
                            Title = "Quiz1"
                        },
                        new
                        {
                            Id = 2,
                            Grade = 0,
                            SectionId = 2,
                            Title = "Quiz2"
                        },
                        new
                        {
                            Id = 3,
                            Grade = 0,
                            SectionId = 3,
                            Title = "Quiz3"
                        },
                        new
                        {
                            Id = 4,
                            Grade = 0,
                            SectionId = 4,
                            Title = "Quiz4"
                        },
                        new
                        {
                            Id = 5,
                            Grade = 0,
                            SectionId = 5,
                            Title = "Quiz5"
                        });
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("LessonsNo")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            LessonsNo = 3,
                            Title = "intro"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            LessonsNo = 5,
                            Title = "OOP"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            LessonsNo = 3,
                            Title = "Binary search"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 3,
                            LessonsNo = 4,
                            Title = "Nutrition"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 4,
                            LessonsNo = 3,
                            Title = "General"
                        });
                });

            modelBuilder.Entity("E_Learning.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linkedin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpirationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Youtube")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0284a6fa-7dca-4c4e-a646-8bdde79ffbf8",
                            Email = "AbdallahShatta@gmail.com",
                            EmailConfirmed = false,
                            FName = "Abdallah",
                            Facebook = "https://www.facebook.com/abdalah.shatta",
                            LName = "Shatta",
                            Linkedin = "https://www.linkedin.com/in/abdallah-shatta55/",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "",
                            RefreshTokenExpirationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74994475-d6ea-412e-b377-b37a8e2b988b",
                            Email = "MohamedErbahim@gmail.com",
                            EmailConfirmed = false,
                            FName = "Mohamed",
                            Facebook = "https://www.facebook.com/mido.ebrahim.9699/",
                            LName = "Ebrahim",
                            Linkedin = "https://www.linkedin.com/in/mohamed-abdelslam210/",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "",
                            RefreshTokenExpirationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fa98f495-bcf7-48d2-aff7-48fb04aa6866",
                            Email = "MohsemTayseer@gmail.com",
                            EmailConfirmed = false,
                            FName = "Mohsen",
                            LName = "Tayseer",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "",
                            RefreshTokenExpirationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "259a9296-58d0-440f-ac62-294f17af1b21",
                            Email = "MarwaElkasaby@gmail.com",
                            EmailConfirmed = false,
                            FName = "Marwa",
                            LName = "Elkasaby",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "",
                            RefreshTokenExpirationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("E_Learning.DAL.Models.WishList", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("WishList");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CourseId = 3,
                            Id = 0
                        },
                        new
                        {
                            UserId = 2,
                            CourseId = 4,
                            Id = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Answer", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Cart", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.Course", "Course")
                        .WithMany("Carts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Learning.DAL.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Course", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning.DAL.Models.User", "User")
                        .WithMany("OwnedCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Enrollment", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Learning.DAL.Models.User", "User")
                        .WithMany("UserEnrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Lesson", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.Section", "Section")
                        .WithMany("Lessons")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Question", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Quiz", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.Section", "Section")
                        .WithMany("Quizes")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Section", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.WishList", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.Course", "Course")
                        .WithMany("WishLists")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Learning.DAL.Models.User", "User")
                        .WithMany("WishListItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("E_Learning.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Course", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Enrollments");

                    b.Navigation("Sections");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.Section", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Quizes");
                });

            modelBuilder.Entity("E_Learning.DAL.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OwnedCourses");

                    b.Navigation("UserEnrollments");

                    b.Navigation("WishListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
